/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShowcaseImport } from './routes/showcase'
import { Route as PublicImport } from './routes/public'
import { Route as DefaultStyleImport } from './routes/default-style'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardListImport } from './routes/_dashboard/list'
import { Route as DashboardDetailImport } from './routes/_dashboard/detail'

// Create/Update Routes

const ShowcaseRoute = ShowcaseImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRoute,
} as any)

const DefaultStyleRoute = DefaultStyleImport.update({
  id: '/default-style',
  path: '/default-style',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardListRoute = DashboardListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDetailRoute = DashboardDetailImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/default-style': {
      id: '/default-style'
      path: '/default-style'
      fullPath: '/default-style'
      preLoaderRoute: typeof DefaultStyleImport
      parentRoute: typeof rootRoute
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/detail': {
      id: '/_dashboard/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof DashboardDetailImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/list': {
      id: '/_dashboard/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof DashboardListImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardDetailRoute: typeof DashboardDetailRoute
  DashboardListRoute: typeof DashboardListRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDetailRoute: DashboardDetailRoute,
  DashboardListRoute: DashboardListRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/default-style': typeof DefaultStyleRoute
  '/public': typeof PublicRoute
  '/showcase': typeof ShowcaseRoute
  '/detail': typeof DashboardDetailRoute
  '/list': typeof DashboardListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DashboardRouteWithChildren
  '/default-style': typeof DefaultStyleRoute
  '/public': typeof PublicRoute
  '/showcase': typeof ShowcaseRoute
  '/detail': typeof DashboardDetailRoute
  '/list': typeof DashboardListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/default-style': typeof DefaultStyleRoute
  '/public': typeof PublicRoute
  '/showcase': typeof ShowcaseRoute
  '/_dashboard/detail': typeof DashboardDetailRoute
  '/_dashboard/list': typeof DashboardListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/default-style'
    | '/public'
    | '/showcase'
    | '/detail'
    | '/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/default-style'
    | '/public'
    | '/showcase'
    | '/detail'
    | '/list'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/default-style'
    | '/public'
    | '/showcase'
    | '/_dashboard/detail'
    | '/_dashboard/list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DefaultStyleRoute: typeof DefaultStyleRoute
  PublicRoute: typeof PublicRoute
  ShowcaseRoute: typeof ShowcaseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DefaultStyleRoute: DefaultStyleRoute,
  PublicRoute: PublicRoute,
  ShowcaseRoute: ShowcaseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboard",
        "/default-style",
        "/public",
        "/showcase"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/detail",
        "/_dashboard/list"
      ]
    },
    "/default-style": {
      "filePath": "default-style.tsx"
    },
    "/public": {
      "filePath": "public.tsx"
    },
    "/showcase": {
      "filePath": "showcase.tsx"
    },
    "/_dashboard/detail": {
      "filePath": "_dashboard/detail.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/list": {
      "filePath": "_dashboard/list.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
